### ISSUE TITLE
Errors when installing install ifx_db

### ISSUE THREAD

**Issue by jenlanham** [ifxdb/node-ifx_db#3]
Hi, 

I am currently running npm version 3.10.8.  Nodejs version 6.8.0.  When I attempt to install ifx_db using:  npm install -g ifx_db, I get the following error:

C:\Program Files\nodejs\node_modules\npm>npm install -g ifx_db

> ifx_db@4.0.4 install ifx_db
> node installer/IfxDriverInstall.js

fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\ifx_db\bin'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at RmDir (C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\ifx_db\installer\IfxDriverInstall.js:186:23)
    at C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\ifx_db\installer\IfxDriverInstall.js:179:17
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ifx_db"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ifx_db@4.0.4 install: `node installer/IfxDriverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ifx_db@4.0.4 install script 'node installer/IfxDriverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ifx_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/IfxDriverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ifx_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ifx_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_modules\npm\npm-debug.log

Is there something that I am doing wrong?

Thanks!

**Comment by msatyan** [comment]
The driver is currently supported up to NodeJS 4x, the NodeJS 6x is planned for early 2017.
